Repository fractalplatform/fractal, pull requests merged in 2019-10, with the labels that each got.

#505 add version cmd compile date info
  cmd/utils/version.go
Labels: enhancement

#504 remove useless code
  common/address.go
  common/bytes.go
  common/bytes_test.go
  common/gaspool_test.go
  common/hash.go
  common/path.go
  common/pubkey.go
Labels: good first issue

#508 increase test coverage common/address
  common/address.go
  common/address_test.go
  common/hash.go
  common/pubkey.go
  consensus/dpos/database.go
  consensus/dpos/database_test.go
Labels: unit test

#507 modify Author json.Marshal
  common/author.go
  common/author_test.go
Labels: enhancement

#509 account testcase
  accountmanager/accountmanager_test.go
Labels: unit test

#510 asset test
  asset/asset_object_test.go
Labels: unit test

#511 fix worker bug
  consensus/miner/worker.go
Labels: bug

#512 fix woker bug
  consensus/miner/worker.go
Labels: bug

#514 fix IsValidateCandidate
  consensus/dpos/dpos.go
Labels: bug

#513 miner skip votecandidate when snapshot block
  consensus/miner/worker.go
Labels: bug

#516 change url ==> info of candidate
  blockchain/genesis.go
  consensus/dpos/api.go
  consensus/dpos/database.go
  consensus/dpos/database_test.go
  consensus/dpos/dpos.go
  consensus/dpos/ldb_test.go
  consensus/dpos/processor.go
  consensus/dpos/vote.go
  sdk/account_test.go
  sdk/test/dpos/createandregcandidate.json
  sdk/test/dpos/dposstartlowc.json
  sdk/test/dpos/dposstartlowq.json
  sdk/test/dpos/dposstartonly.json
  sdk/test/dpos/regcandidate.json
  sdk/test/dpos/updatecandidate.json
  sdk/test/sample.go
  sdk/test/sample.json
  sdk/test/testcase/dpos/0001regcandidate.json
  sdk/test/testcase/dpos/0002updatecandidate.json
  sdk/test/testcase/dpos/0003unregcandidate.json
  sdk/test/testcase/dpos/0004votecandidate.json
  sdk/test/testcase/dpos/0005refundcandidate.json
  sdk/test/testcase/dpos/0006kickedcandidate.json
  test/common/dpos.go
Labels: bug, enhancement

#517 blockchain/downloader: change log message
  Makefile
  blockchain/downloader.go
Labels: enhancement

#519 p2p/protoadaptor: fixed ddos check error
  p2p/protoadaptor/ProtoAdaptor.go
Labels: bug
