Repository fractalplatform/fractal, pull requests merged in 2019-03, with the labels that each got.

#51 fix blockchain fork chain validate header error
  blockchain/blockchain.go
  processor/validator.go
Labels: bug

#52 remove reorg state when the blockchain forking
  blockchain/blockchain.go
Labels: bug

#54 Fork
  blockchain/blockchain.go
  blockchain/blockchain_insert.go
  blockchain/downloader.go
  blockchain/forkcontroller.go
  blockchain/forkcontroller_test.go
  blockchain/gen_genesis.go
  blockchain/test_utils.go
  consensus/consensus.go
  consensus/dpos/dpos.go
  consensus/miner/worker.go
  params/chainconfig.go
  processor/evm.go
  processor/validator.go
  types/block.go
  types/block_test.go
Labels: enhancement

#62 fix extra reward bug
  consensus/dpos/dpos.go
Labels: bug

#65 support import/export block
  blockchain/blockchain.go
  cmd/ft/chaincmd.go
  ftservice/ftservice.go
  node/node.go
  processor/error.go
  processor/validator.go
  state/statedb.go
  state/statedb_test.go
  types/block.go
  types/optinfo.go
  utils/trie/database.go
  utils/trie/encoding.go
  utils/trie/encoding_test.go
  utils/trie/errors.go
  utils/trie/hasher.go
  utils/trie/iterator.go
  utils/trie/iterator_test.go
  utils/trie/node.go
  utils/trie/node_test.go
  utils/trie/proof.go
  utils/trie/proof_test.go
  utils/trie/secure_trie.go
  utils/trie/secure_trie_test.go
  utils/trie/sync.go
  utils/trie/sync_test.go
  utils/trie/trie.go
  utils/trie/trie_test.go
Labels: enhancement

#55 ftserver contract log storage
  blockchain/blockchain.go
  cmd/ft/default.go
  cmd/ft/root.go
  ftservice/apibackend.go
  ftservice/config.go
  ftservice/ftservice.go
  internal/api/backend.go
  internal/api/blockchain.go
  processor/processor.go
  processor/vm/instructions.go
  processor/vm/interpreter.go
  processor/vm/vm.go
  rawdb/accessors_chain.go
  rawdb/schema.go
  test/common/utils.go
  test/contract/MultiAsset/transaction_contract.go
  test/tx/contract_log_query.go
  types/internal.go
  types/receipt.go
Labels: enhancement

#86 add cadidate counter
  blockchain/genesis_test.go
  consensus/consensus.go
  consensus/dpos/api.go
  consensus/dpos/database.go
  consensus/dpos/dpos.go
  consensus/dpos/ldb.go
  consensus/dpos/vote.go
  processor/evm.go
  processor/vm/instructions.go
  processor/vm/runtime/runtime.go
  processor/vm/vm.go
  test.sh
Labels: enhancement

#87 support subaccount and subasset
  accountmanager/account.go
  accountmanager/accountmanager.go
  accountmanager/accountmanager_test.go
  accountmanager/config.go
  accountmanager/error.go
  asset/asset.go
  asset/asset_object.go
  asset/asset_test.go
  asset/config.go
  blockchain/genesis.go
  cmd/ft/default.go
  common/name.go
  common/name_test.go
  consensus/dpos/dpos.go
  consensus/miner/miner.go
  consensus/miner/worker.go
  ftservice/config.go
  ftservice/ftservice.go
  rawdb/accessors_chain_test.go
  txpool/txpool_test.go
Labels: enhancement

#88 fix bug
  blockchain/blockchain.go
  consensus/dpos/api.go
  consensus/dpos/dpos.go
  consensus/miner/worker.go
Labels: bug

#99 modify get block detail log rpc
  ftservice/apibackend.go
  internal/api/backend.go
  internal/api/blockchain.go
  types/internal.go
Labels: enhancement

#97 change to multi signature
  accountmanager/account.go
  accountmanager/account_test.go
  accountmanager/accountmanager.go
  accountmanager/accountmanager_test.go
  blockchain/genesis_test.go
  blockchain/test_utils.go
  common/address.go
  common/author.go
  consensus/dpos/dpos.go
  consensus/miner/worker.go
  ftservice/apibackend.go
  internal/api/fractal.go
  processor/evm.go
  processor/processor.go
  processor/vm/runtime/runtime.go
  processor/vm/vm.go
  sdk/account.go
  sdk/api_account.go
  test/common/dpos.go
  test/multisig/transaction_contract.go
  txpool/sendercacher.go
  txpool/test_utils.go
  txpool/txpool_test.go
  txpool/utils.go
  types/action.go
  types/signer.go
  types/signer_test.go
  wallet/wallet.go
Labels: enhancement

#95 fix bug
  accountmanager/accountmanager.go
  blockchain/blockchain_test.go
  blockchain/blockgenerator.go
  blockchain/genesis_test.go
  blockchain/test_utils.go
  consensus/dpos/database.go
  consensus/dpos/dpos.go
  consensus/dpos/processor.go
  consensus/dpos/vote.go
  consensus/miner/worker.go
  processor/transition.go
  sdk/account.go
  sdk/account_test.go
  sdk/api_ft_test.go
  test.sh
  test/dposstart/main.go
  types/action.go
Labels: enhancement

#100 add transaction test
  blockchain/blockchain.go
  processor/vm/instructions.go
  test/contract/MultiAsset/MultiAsset.abi
  test/contract/MultiAsset/MultiAsset.bin
  test/contract/MultiAsset/MultiAsset.sol
  test/contract/MultiAsset/transaction_contract.go
  test/contract/VEN/transaction_contract.go
  test/transaction/sendtransaction.go
  test/tx/contract_log_query.go
  test/tx/main.go
Labels: bug, enhancement

#101 Dev
  ftservice/apibackend.go
  internal/api/backend.go
  internal/api/blockchain.go
Labels: enhancement

#106 bloom encoding
  internal/api/blockchain.go
Labels: bug

#107 delete useless gas params
  accountmanager/accountmanager.go
  params/params.go
  processor/vm/gas_table.go
  txpool/utils.go
Labels: bug, enhancement

#110 modify snapshot
  cmd/ft/root.go
  ftservice/ftservice.go
  params/gas_table.go
  processor/vm/gas_table.go
  processor/vm/instructions.go
  processor/vm/jump_table.go
  processor/vm/opcodes.go
  state/statedb.go
  state/statedb_test.go
Labels: bug
