Repository fractalplatform/fractal, pull requests merged in 2019-07, with the labels that each got.

#379 Magic net ID
  ftservice/ftservice.go
  p2p/discover/udp.go
  p2p/discover/udp_test.go
  p2p/protoadaptor/ProtoAdaptor.go
  p2p/rlpx.go
  p2p/rlpx_test.go
  p2p/server.go
  p2p/server_test.go
Labels: enhancement

#378 move TxPool reorg and events to background goroutine
  blockchain/genesis.go
  rpcapi/p2p.go
  txpool/accountset.go
  txpool/config.go
  txpool/handler_test.go
  txpool/nameheartbeat.go
  txpool/pricedlsit.go
  txpool/test_utils.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: bug, enhancement

#384 modify blockchain start err
  blockchain/blockchain.go
Labels: bug

#388 Fix uint infinite loop
  ftservice/apibackend.go
Labels: bug

#383 delete log
  processor/vm/instructions.go
Labels: bug

#387 modify fork controller some logic
  blockchain/blockchain.go
  blockchain/forkcontroller.go
  blockchain/forkcontroller_test.go
Labels: bug, enhancement

#392 Ftfinder
  cmd/ftfinder/root.go
  node/config.go
  p2p/server.go
Labels: bug

#393 Dposfork
  consensus/dpos/api.go
  consensus/dpos/database.go
  nodes.txt
Labels: enhancement

#408 blockchain store irreversible number
  blockchain/blockchain.go
Labels: bug

#411 fixed txpool test failed in travis CI
  txpool/txpool_test.go
Labels: bug

#412 update dpos api
  consensus/dpos/api.go
  consensus/dpos/database.go
Labels: bug, enhancement
