Repository fractalplatform/fractal, pull requests merged in 2019-05, with the labels that each got.

#214 modify name for support more scenes
  accountmanager/account.go
  accountmanager/accountmanager.go
  accountmanager/accountmanager_test.go
  asset/asset.go
  asset/asset_object.go
  blockchain/genesis.go
  blockchain/genesis_test.go
  common/name.go
  common/name_test.go
  consensus/dpos/dpos.go
  consensus/miner/miner.go
  consensus/miner/worker.go
  feemanager/fee.go
  params/chainconfig.go
  processor/vm/instructions.go
  test/dposstart/main.go
Labels: bug

#221 execWithdrawFee return err when fm.WithdrawFeeFromSystem fail
  processor/vm/instructions.go
Labels: bug

#222 fix fork contracl init err
  blockchain/blockchain.go
  blockchain/forkcontroller.go
  blockchain/forkcontroller_test.go
  blockchain/genesis.go
  blockchain/genesis_test.go
  blockchain/handler.go
Labels: bug

#225 add json unmarshal for author
  common/author.go
Labels: bug

#235 change issueasset struct
  processor/vm/instructions.go
  test/fee/transaction_contract.go
Labels: bug

#238 fix candidate reward
  consensus/dpos/api.go
  consensus/dpos/dpos.go
  consensus/dpos/vote.go
Labels: bug

#246 P2p dns
  p2p/enode/urlv4.go
  p2p/enode/urlv4_test.go
  p2p/protoadaptor/ProtoAdaptor.go
Labels: bug

#247 sign remark and assetid
  test/fee/transaction_contract.go
  types/signer.go
Labels: bug

#250 crypto: add some comments
  crypto/ecies/ecies.go
Labels: bug

#251 add gas price oracle unit test
  ftservice/gasprice/gasprice.go
  ftservice/gasprice/gasprice_test.go
  params/unit.go
Labels: bug

#253 add sha3 sync.pool
  blockchain/blockchain.go
  common/address.go
  common/gaspool_test.go
  common/merkle.go
  common/merkle_test.go
  common/path.go
  common/sha3pool.go
  crypto/crypto.go
  p2p/enode/idscheme.go
  p2p/enode/urlv4_test.go
  types/block.go
Labels: enhancement

#254 Jacob fix
  processor/vm/vm.go
Labels: bug

#257 modify genesis.json not support create subaccount
  build/genesis.json
  build/testnet.json
Labels: enhancement

#258 change genesis gas limit to 30million
  blockchain/genesis_test.go
  params/params.go
Labels: bug

#259 move gas to GasTableInstanse
  consensus/miner/worker.go
  params/gas_table.go
  params/params.go
  processor/transition.go
  processor/vm/gas.go
  processor/vm/gas_table.go
  processor/vm/instructions.go
  processor/vm/interpreter.go
  processor/vm/jump_table.go
  processor/vm/vm.go
  rpcapi/blockchain.go
  sdk/account_test.go
  txpool/txpool_test.go
  txpool/utils.go
Labels: bug

#261 Gas fix
  processor/vm/contract.go
  processor/vm/contracts.go
  processor/vm/instructions.go
  processor/vm/vm.go
Labels: bug

#262 fix dpos
  consensus/dpos/dpos.go
  consensus/dpos/ldb.go
  processor/vm/instructions.go
Labels: bug

#265 fix bug when dpos started
  consensus/dpos/vote.go
Labels: bug

#267 change withdraw type to transfer
  processor/vm/instructions.go
Labels: bug

#268 Check code
  accountmanager/account.go
  accountmanager/accountmanager.go
  asset/asset.go
  blockchain/blockchain.go
  blockchain/downloader.go
  blockchain/error.go
  blockchain/forkcontroller.go
  blockchain/gen_genesis_test.go
  blockchain/genesis.go
  blockchain/genesis_test.go
  cmd/ft/miner.go
  common/name_test.go
  consensus/miner/worker.go
  event/router_test.go
  feemanager/fee.go
  ftservice/ftservice.go
  p2p/server.go
  processor/vm/instructions.go
  processor/vm/log.go
  processor/vm/memory.go
  processor/vm/vm.go
  rpc/client.go
  snapshot/snapshot.go
  state/statedb.go
  types/action.go
  types/signer.go
  types/signer_test.go
Labels: bug

#278 Makefile: fixed bug of target 'build_workspace'
  Makefile
Labels: bug

#279 add read yaml and toml test
  accountmanager/account.go
  build/eg_config.yaml
  cmd/ft/root.go
  cmd/ft/root_test.go
  cmd/ft/test/config.toml
  cmd/ft/test/config.yaml
  p2p/server.go
Labels: bug

#289 Sdk contract
  sdk/account.go
  sdk/account_test.go
  sdk/api_account.go
  sdk/test/Asset.abi
  sdk/test/Asset.bin
  sdk/test/asset.sol
  txpool/txpool.go
Labels: enhancement

#291 modify gas distribution
  accountmanager/account.go
  accountmanager/accountmanager.go
  blockchain/genesis_test.go
  build/eg_config.yaml
  cmd/ft/flags.go
  cmd/ft/root_test.go
  cmd/ft/test/config.toml
  cmd/ft/test/config.yaml
  params/chainconfig.go
  params/gas_table.go
  processor/transition.go
  processor/vm/vm.go
  test/fee/transaction_contract.go
  test/multisig/transaction_contract.go
  txpool/config.go
  txpool/handler.go
  txpool/handler_test.go
  txpool/txpool.go
  txpool/txpool_test.go
  txpool/utils.go
  vendor/github.com/ethereum/go-ethereum/log/format.go
  vendor/github.com/ethereum/go-ethereum/log/handler.go
  vendor/github.com/mattn/go-runewidth/LICENSE
  vendor/github.com/mattn/go-runewidth/README.mkd
  vendor/github.com/mattn/go-runewidth/go.mod
  vendor/github.com/mattn/go-runewidth/runewidth.go
  vendor/github.com/mattn/go-runewidth/runewidth_appengine.go
  vendor/github.com/mattn/go-runewidth/runewidth_js.go
  vendor/github.com/mattn/go-runewidth/runewidth_posix.go
  vendor/github.com/mattn/go-runewidth/runewidth_windows.go
  vendor/github.com/peterh/liner/COPYING
  vendor/github.com/peterh/liner/README.md
  vendor/github.com/peterh/liner/bsdinput.go
  vendor/github.com/peterh/liner/common.go
  vendor/github.com/peterh/liner/fallbackinput.go
  vendor/github.com/peterh/liner/go.mod
  vendor/github.com/peterh/liner/go.sum
  vendor/github.com/peterh/liner/input.go
  vendor/github.com/peterh/liner/input_darwin.go
  vendor/github.com/peterh/liner/input_linux.go
  vendor/github.com/peterh/liner/input_windows.go
  vendor/github.com/peterh/liner/line.go
  vendor/github.com/peterh/liner/output.go
  vendor/github.com/peterh/liner/output_windows.go
  vendor/github.com/peterh/liner/unixmode.go
  vendor/github.com/peterh/liner/width.go
  vendor/vendor.json
Labels: bug, enhancement

#292 fix bug that internal transfer fails
  processor/transition.go
  processor/vm/instructions.go
Labels: bug

#295 fix actual counter of candidate
  consensus/dpos/dpos.go
  consensus/dpos/vote.go
Labels: bug

#304 fix block chain fork bug
  blockchain/blockchain.go
  blockchain/blockgenerator.go
  blockchain/test_utils.go
  consensus/consensus.go
  consensus/miner/worker.go
  processor/evm.go
  processor/transition.go
  processor/validator.go
  processor/vm/vm.go
Labels: bug

#303 modify contract asset issue/asset, transferasset
  accountmanager/accountmanager.go
  accountmanager/error.go
  asset/asset.go
  ftservice/apibackend.go
  processor/evm.go
  processor/processor.go
  processor/vm/instructions.go
  processor/vm/jump_table.go
  processor/vm/opcodes.go
  processor/vm/vm.go
  rpcapi/backend.go
  rpcapi/blockchain.go
  types/accountmanage.go
  types/action.go
Labels: bug, enhancement

#305 fix should counter of candidate
  consensus/dpos/dpos.go
  consensus/dpos/vote.go
  sdk/test/dpos/createcandidate.json
  sdk/test/dpos/dposstartlowc.json
  sdk/test/dpos/dposstartlowq.json
  sdk/test/dpos/dposstartonly.json
  sdk/test/dpos/kickedcandidate.json
  sdk/test/dpos/refoundcandidate.json
  sdk/test/dpos/regcandidate.json
  sdk/test/dpos/unregcandidate.json
  sdk/test/dpos/updatecandidate.json
  sdk/test/dpos/votecandidate.json
  sdk/test/main.go
  sdk/test/testcase/dpos/0006kickedcandidate.json
Labels: bug
