Repository fractalplatform/fractal, pull requests merged in 2019-04, with the labels that each got.

#170 fixed restart node missmatch genesis block hash
  blockchain/genesis.go
  cmd/ft/root.go
Labels: bug

#171 modify newaction param assetID
  accountmanager/accountmanager.go
  consensus/dpos/processor.go
Labels: bug

#172 add deductgas api
  params/gas_table.go
  processor/vm/gas_table.go
  processor/vm/instructions.go
  processor/vm/jump_table.go
  processor/vm/opcodes.go
Labels: enhancement

#177 modify state pruning
  blockchain/blockchain.go
  blockchain/genesis_test.go
  blockchain/test_utils.go
  build/genesis.json
  build/testnet.json
  cmd/ft/config.go
  cmd/ft/flags.go
  common/prque/prque.go
  common/prque/sstack.go
  ftservice/apibackend.go
  ftservice/config.go
  ftservice/ftservice.go
  params/chainconfig.go
  rpcapi/backend.go
  rpcapi/blockchain.go
  state/statedb.go
  state/statedb_test.go
  types/block.go
Labels: enhancement

#176 fix dpos
  blockchain/blockchain.go
  blockchain/blockchain_test.go
  blockchain/genesis.go
  blockchain/genesis_test.go
  blockchain/test_utils.go
  build/genesis.json
  build/testnet.json
  consensus/consensus.go
  consensus/dpos/api.go
  consensus/dpos/config.go
  consensus/dpos/config_test.go
  consensus/dpos/database.go
  consensus/dpos/database_test.go
  consensus/dpos/dpos.go
  consensus/dpos/ldb.go
  consensus/dpos/ldb_test.go
  consensus/dpos/processor.go
  consensus/dpos/vote.go
  consensus/dpos/vote_test.go
  consensus/miner/worker.go
  ftservice/ftservice.go
  params/chainconfig.go
  processor/evm.go
  processor/processor.go
  processor/transition.go
  rpcapi/blockchain.go
  sdk/account.go
  sdk/account_test.go
  sdk/accountck.go
  sdk/api_dpos.go
  sdk/api_dpos_test.go
  test/common/dpos.go
  test/dposstart/main.go
  types/action.go
Labels: bug, enhancement

#173 Verifying permissions
  .gitignore
  accountmanager/account.go
  accountmanager/accountmanager.go
  blockchain/blockchain.go
  blockchain/genesis_test.go
  build/eg_config.yaml
  test/common/dpos.go
  test/multisig/transaction_contract.go
  txpool/list.go
  txpool/txpool.go
  txpool/txpool_test.go
  txpool/utils.go
  types/action.go
  types/action_test.go
  types/block.go
  types/receipt.go
  types/signer.go
  types/signer_test.go
  types/transaction.go
Labels: bug

#183 generate author version when account create
  accountmanager/account.go
  blockchain/genesis_test.go
  test/multisig/transaction_contract.go
Labels: bug

#184 fix dpos
  consensus/dpos/api.go
  consensus/dpos/processor.go
  consensus/dpos/vote.go
  types/action.go
Labels: bug

#191 add debug pprof,trace cmd flags and rpc
  build/eg_config.yaml
  cmd/ft/config.go
  cmd/ft/flags.go
  cmd/ft/root.go
  cmd/utils/logconfig.go
  debug/api.go
  debug/flags.go
  debug/loudpanic.go
  debug/trace.go
  rpcapi/backend.go
  vendor/github.com/fjl/memsize/LICENSE
  vendor/github.com/fjl/memsize/bitmap.go
  vendor/github.com/fjl/memsize/doc.go
  vendor/github.com/fjl/memsize/go.mod
  vendor/github.com/fjl/memsize/memsize.go
  vendor/github.com/fjl/memsize/memsizeui/template.go
  vendor/github.com/fjl/memsize/memsizeui/ui.go
  vendor/github.com/fjl/memsize/runtimefunc.go
  vendor/github.com/fjl/memsize/runtimefunc.s
  vendor/github.com/fjl/memsize/type.go
  vendor/vendor.json
Labels: enhancement

#187 fix dpos
  consensus/dpos/api.go
  consensus/dpos/config.go
  consensus/dpos/database.go
  consensus/dpos/dpos.go
  consensus/dpos/ldb.go
  consensus/dpos/ldb_test.go
  consensus/dpos/vote.go
  processor/transition.go
Labels: bug

#195 fix dpos
  consensus/dpos/api.go
  consensus/dpos/processor.go
  consensus/dpos/vote.go
  sdk/api_ft.go
  sdk/api_ft_test.go
Labels: bug

#196 add feemanager test examples
  common/author.go
  test/fee/MultiAsset.abi
  test/fee/MultiAsset.bin
  test/fee/MultiAsset.sol
  test/fee/WithdrawFee.abi
  test/fee/WithdrawFee.bin
  test/fee/transaction_contract.go
  test/fee/withdraw.sol
Labels: enhancement

#198 add TTL to tx broadcast
  blockchain/handler.go
  event/router.go
  ftservice/apibackend.go
  p2p/discover/table.go
  p2p/discover/table_test.go
  p2p/discover/table_util_test.go
  p2p/discover/udp.go
  p2p/discover/udp_test.go
  p2p/peer_error.go
  p2p/protoadaptor/ProtoAdaptor.go
  p2p/rlpx.go
  p2p/rlpx_test.go
  p2p/server.go
  p2p/server_test.go
  rpcapi/backend.go
  rpcapi/p2p.go
  txpool/handler.go
  txpool/handler_test.go
  txpool/protocol.go
  txpool/txpool.go
Labels: bug, duplicate

#206 rename debug/flags.go => debug/config.go
  cmd/ft/init.go
  cmd/ftfinder/config.go
  debug/api.go
  debug/config.go
  processor/vm/log.go
  rpcapi/blockchain.go
  txpool/txpool_test.go
Labels: bug

#208 add action remark field
  accountmanager/accountmanager.go
  accountmanager/accountmanager_test.go
  blockchain/genesis.go
  blockchain/genesis_test.go
  blockchain/test_utils.go
  consensus/dpos/dpos.go
  processor/processor.go
  processor/vm/instructions.go
  processor/vm/runtime/run_test.go
  processor/vm/runtime/runtime_test.go
  rawdb/accessors_chain_test.go
  rawdb/accessors_indexes_test.go
  rpcapi/blockchain.go
  sdk/account.go
  test/common/dpos.go
  test/contract/MultiAsset/transaction_contract.go
  test/contract/VEN/transaction_contract.go
  test/dposstart/main.go
  test/fee/transaction_contract.go
  test/multisig/transaction_contract.go
  test/transaction/sendtransaction.go
  txpool/config.go
  txpool/handler_test.go
  txpool/priceheap_test.go
  txpool/test_utils.go
  txpool/tx_journal_test.go
  txpool/txpool.go
  txpool/txpool_test.go
  txpool/utils.go
  types/action.go
  types/action_test.go
Labels: duplicate

#205 disbale other account create subaccount
  accountmanager/accountmanager.go
  snapshot/snapshot_test.go
Labels: bug

#211 evm push accoutid into stack rather than name
  processor/vm/instructions.go
  test/fee/WithdrawFee.abi
  test/fee/WithdrawFee.bin
Labels: bug

#213 fix txpool gas seet
  txpool/txpool.go
Labels: bug

#212 add Fee json
  feemanager/fee.go
  rpcapi/fee.go
Labels: bug

#210 Txs handler
  txpool/handler.go
  txpool/handler_test.go
  txpool/protocol.go
Labels: bug
