Repository fractalplatform/fractal, pull requests merged in 2019-08, with the labels that each got.

#417 modify gas price oracle
  build/eg_config.yaml
  cmd/ft/config.go
  cmd/ft/flags.go
  cmd/ft/test/config.toml
  cmd/ft/test/config.yaml
  ftservice/gasprice/gasprice.go
  ftservice/gasprice/gasprice_test.go
Labels: bug, enhancement

#423 fixed txpool add remotes not check the same tx was exist
  ftservice/apibackend.go
  ftservice/gasprice/gasprice.go
  ftservice/gasprice/gasprice_test.go
  rpcapi/backend.go
  rpcapi/blockchain.go
  txpool/txpool.go
Labels: bug

#425 add callwithpay
  processor/vm/jump_table.go
  processor/vm/opcodes.go
Labels: enhancement

#428 modify api get account by name and id
  rpcapi/account.go
  sdk/api_account.go
Labels: enhancement

#430 fied txpool rpc send same tx err
  txpool/txpool.go
Labels: bug

#431 add filters rpc
  ftservice/apibackend.go
  rpcapi/backend.go
  rpcapi/filters/api.go
  rpcapi/filters/api_test.go
  rpcapi/filters/filter.go
  rpcapi/filters/filter_system.go
  rpcapi/filters/filter_system_test.go
Labels: enhancement

#432 Rpc wallet interface
  consensus/consensus.go
  ftservice/apibackend.go
  rpcapi/backend.go
  rpcapi/blockchain.go
  types/internal.go
Labels: bug, enhancement

#434 Vmfix
  processor/vm/interpreter.go
  processor/vm/jump_table.go
  processor/vm/memory_table.go
  processor/vm/opcodes.go
  processor/vm/vm_test.go
Labels: bug

#433 naming
  ftservice/apibackend.go
  test/common/blockchain.go
  types/internal.go
Labels: bug

#439 P2p
  blockchain/downloader.go
  blockchain/handler.go
  blockchain/handler_test.go
  cmd/ft/config.go
  cmd/ft/flags.go
  cmd/ftfinder/root.go
  event/router.go
  go.mod
  node/config.go
  node/node.go
  p2p/enode/urlv4.go
  p2p/server.go
  txpool/lookup_test.go
Labels: bug, enhancement

#440 fix rpc outut format
  rpcapi/blockchain.go
  rpcapi/filters/api.go
Labels: bug

#438 updae vote restrict
  consensus/dpos/api.go
Labels: bug

#442 blockchain/downloader: add testcase
  blockchain/downloader_test.go
  blockchain/handler_test.go
Labels: enhancement

#449 increase test cover
  consensus/dpos/ldb_test.go
Labels: unit test

#446 add some doc of intefaces in consensus
  consensus/consensus.go
Labels: note

#450 blockchain: fixed a bug in testcase
  blockchain/downloader_test.go
  blockchain/handler.go
  blockchain/handler_test.go
  blockchain/test_utils.go
Labels: unit test

#448 add state test
  state/statedb_test.go
Labels: unit test

#447 test asset after fork
  accountmanager/accountmanager_test.go
Labels: unit test

#451 fix TestAsset
  processor/vm/runtime/contract/Asset/Asset.abi
  processor/vm/runtime/contract/Asset/Asset.bin
  processor/vm/runtime/contract/Asset/Asset.sol
  processor/vm/runtime/runtime_test.go
Labels: unit test

#452 modify account misspelling
  accountmanager/account.go
  accountmanager/accountmanager.go
  accountmanager/accountmanager_test.go
  accountmanager/error.go
  accountmanager/interface.go
  asset/asset.go
  asset/asset_object.go
  asset/asset_object_test.go
  asset/asset_test.go
  asset/error.go
  asset/interface.go
  blockchain/blockchain_insert.go
  blockchain/genesis.go
  blockchain/test_utils.go
  consensus/dpos/api.go
  consensus/dpos/processor.go
  processor/vm/contract.go
  processor/vm/instructions.go
  sdk/account.go
  sdk/account_test.go
Labels: good first issue

#454 review miner module
  consensus/miner/api.go
  consensus/miner/miner.go
  consensus/miner/worker.go
Labels: note
