Repository fractalplatform/fractal, pull requests merged in 2019-09, with the labels that each got.

#453 add state test
  state/statedb.go
  state/statedb_test.go
Labels: unit test

#456 add test for contract VEN
  processor/vm/runtime/contract/Ven/VEN.bin
  processor/vm/runtime/contract/Ven/VEN.sol
  processor/vm/runtime/contract/Ven/VENSale.bin
  processor/vm/runtime/runtime_test.go
Labels: unit test

#457 modify blockchain misspelling and change ft_getTransactions
  accountmanager/interface.go
  blockchain/blockchain.go
  blockchain/downloader.go
  blockchain/genesis.go
  blockchain/handler.go
  blockchain/handler_test.go
  blockchain/protocol.go
  cmd/ft/chain.go
  cmd/ft/miner.go
  cmd/ft/utils.go
  cmd/utils/history.go
  common/name.go
  consensus/miner/worker.go
  feemanager/fee.go
  ftservice/ftservice.go
  params/gas_table.go
  processor/error.go
  processor/transition.go
  processor/vm/instructions.go
  processor/vm/interpreter.go
  processor/vm/stack.go
  processor/vm/vm_test.go
  rpcapi/account.go
  rpcapi/blockchain.go
  rpcapi/p2p.go
  state/statedb.go
  txpool/utils.go
Labels: enhancement

#458 dpos review
  consensus/dpos/api.go
  consensus/dpos/config.go
  consensus/dpos/database.go
  consensus/dpos/dpos.go
  consensus/dpos/ldb_test.go
Labels: note

#459 add vm tests
  processor/vm/vm_example_test.go
Labels: unit test

#461 p2p/enode: add bootnode parsing testcase
  p2p/enode/urlv4_test.go
Labels: unit test

#464 modify setStatePruning rpc private
  cmd/ft/chain.go
  rpcapi/backend.go
Labels: enhancement

#463 add rpc api ft__forkStatus
  accountmanager/accountmanager.go
  accountmanager/accountmanager_test.go
  blockchain/blockchain.go
  blockchain/forkcontroller.go
  ftservice/apibackend.go
  rpcapi/account.go
  rpcapi/backend.go
  rpcapi/blockchain.go
  sdk/account.go
  sdk/account_test.go
  sdk/test/sample.go
Labels: enhancement

#462 withdraw fee not exsit
  feemanager/fee_test.go
Labels: unit test

#465 Increase test cover
  consensus/dpos/database_test.go
Labels: unit test

#466 params: add ChainConfig.Copy() testcase
  params/chainconifg_test.go
Labels: unit test

#467 add test for dpos db
  consensus/dpos/ldb_test.go
Labels: unit test

#469 blockchain/downloader: fiexd bug that may don't download the new blcok
  blockchain/downloader.go
Labels: bug

#468 add chain command forkstatus
  cmd/ft/chain.go
Labels: enhancement

#471 add snapshot test
  snapshot/snapshot_test.go
Labels: unit test

#472 account test case
  accountmanager/accountmanager_test.go
Labels: unit test

#473 Increase test cover
  consensus/dpos/config_test.go
Labels: unit test

#474 Blockchain bug
  blockchain/blockchain.go
  rawdb/schema.go
Labels: bug

#475 modify txpool test
  txpool/config.go
  txpool/handler_test.go
  txpool/test_utils.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: unit test

#476 Increase test cover
  common/size_test.go
Labels: unit test

#478 modify blockchain unit test
  blockchain/blockchain_test.go
  blockchain/blockgenerator.go
  blockchain/downloader.go
  blockchain/downloader_test.go
  blockchain/events.go
  blockchain/handler_test.go
  blockchain/test_utils.go
Labels: unit test

#482 increase dpos unit test
  consensus/dpos/vote_test.go
Labels: unit test

#481 blockchain/downloader: fixed bug that broadcast wrong block
  blockchain/downloader.go
Labels: bug

#483 consensus/miner: let code more clear
  consensus/miner/miner.go
  consensus/miner/worker.go
  ftservice/ftservice.go
Labels: enhancement

#485 add blockchain test
  blockchain/blockgenerator.go
  blockchain/test_utils.go
  event/router.go
Labels: unit test

#486 set the minimum price
  ftservice/gasprice/gasprice.go
  ftservice/gasprice/gasprice_test.go
Labels: bug

#490 Downloader
  blockchain/downloader.go
Labels: bug

#493 add blockchain badHash test
  blockchain/blockchain.go
  blockchain/blockchain_test.go
Labels: unit test

#491 Dposrpc1
  consensus/dpos/api.go
  consensus/dpos/database.go
Labels: enhancement

#492 Increase test cover
  consensus/dpos/config_test.go
Labels: unit test

#496 p2p,rpc: add rpc to query seed nodes from db
  ftservice/apibackend.go
  p2p/dial.go
  p2p/dial_test.go
  p2p/discover/table.go
  p2p/enode/nodedb.go
  p2p/server.go
  rpcapi/backend.go
  rpcapi/p2p.go
Labels: enhancement

#495 fee transfer internal record
  processor/transition.go
  processor/vm/instructions.go
Labels: enhancement

#497 cmd/ft: add method 'seednodes' into sub-cmd 'p2p'
  cmd/ft/p2p.go
  cmd/ft/utils.go
  cmd/ftfinder/root.go
  cmd/ftfinder/rpc.go
  p2p/server.go
  rpc/client.go
Labels: enhancement

#498 export error
  accountmanager/accountmanager.go
  blockchain/genesis.go
  cmd/ft/root.go
  ftservice/ftservice.go
Labels: bug

#501 modify gas price
  consensus/miner/miner.go
  txpool/config.go
Labels: enhancement

#502 add txpool cmd gettxsbyaccount
  cmd/ft/txpool.go
  rpcapi/txpool.go
Labels: enhancement

#500 add setcoinbase check
  consensus/miner/worker.go
Labels: enhancement

#499 fix miner bug
  consensus/miner/worker.go
Labels: bug

#503 p2p: fixed bug that may close a nil channel
  cmd/ftfinder/root.go
  p2p/server.go
Labels: bug
