Repository fractalplatform/fractal, pull requests merged in 2019-06, with the labels that each got.

#307 candidate info saved by epoch & rpc api
  blockchain/genesis.go
  blockchain/genesis_test.go
  blockchain/test_utils.go
  build/genesis.json
  build/testnet.json
  consensus/dpos/api.go
  consensus/dpos/config.go
  consensus/dpos/database.go
  consensus/dpos/dpos.go
  consensus/dpos/ldb.go
  consensus/dpos/ldb_test.go
  consensus/dpos/processor.go
  consensus/dpos/vote.go
  consensus/dpos/vote_test.go
  params/chainconfig.go
  processor/vm/runtime/runtime.go
  processor/vm/vm.go
  sdk/api_dpos.go
  sdk/api_dpos_test.go
  sdk/test/main.go
  test/blockstatistic/main.go
Labels: bug

#314 fix distribute gas using bigInt
  params/gas_table.go
  processor/vm/vm.go
Labels: bug

#317 fix miner worker mem out of range
  consensus/miner/worker.go
Labels: bug

#320 delete useless tests
  test/contract/MultiAsset/MultiAsset.abi
  test/contract/MultiAsset/MultiAsset.bin
  test/contract/MultiAsset/MultiAsset.sol
  test/contract/MultiAsset/transaction_contract.go
  test/contract/VEN/VEN.abi
  test/contract/VEN/VEN.bin
  test/contract/VEN/VENSale.abi
  test/contract/VEN/VENSale.bin
  test/contract/VEN/transaction_contract.go
  test/dposstart/main.go
  test/transaction/sendtransaction.go
Labels: bug

#321 txpool and downloader
  blockchain/downloader.go
  p2p/protoadaptor/ProtoAdaptor.go
  txpool/handler.go
Labels: bug, enhancement

#324 fix should counter
  consensus/dpos/config.go
Labels: bug

#332 Account
  accountmanager/accountmanager.go
  common/name.go
  common/name_test.go
Labels: bug

#333 add getassetid api
  accountmanager/accountmanager.go
  params/gas_table.go
  processor/vm/gas_table.go
  processor/vm/instructions.go
  processor/vm/jump_table.go
  processor/vm/opcodes.go
  processor/vm/runtime/contract/crypto/testcrypto.abi
  processor/vm/runtime/run_test.go
Labels: bug, enhancement

#337 modify subasset decimals
  accountmanager/accountmanager.go
  asset/asset.go
Labels: bug

#340 Dev crash debug
  blockchain/downloader.go
  blockchain/handler.go
  p2p/protoadaptor/ProtoAdaptor.go
  txpool/handler.go
Labels: bug

#341 Blockchain
  Makefile
  blockchain/blockchain.go
  processor/validator.go
  state/mtp/database.go
Labels: bug

#342 Badblockhashes
  blockchain/blockchain.go
  blockchain/error.go
  blockchain/test_utils.go
  build/eg_config.yaml
  cmd/ft/flags.go
  cmd/ft/test/config.toml
  cmd/ft/test/config.yaml
  ftservice/config.go
  ftservice/ftservice.go
Labels: bug, enhancement

#344 fix state store irreversible number err
  blockchain/blockchain.go
  txpool/txpool.go
Labels: bug

#346 Downloader
  blockchain/blockchain.go
  blockchain/downloader.go
  txpool/txpool.go
Labels: bug

#347 Downloader
  blockchain/downloader.go
Labels: bug

#352 Pending
  cmd/ft/debug.go
  cmd/ft/txpool.go
  cmd/ft/utils.go
  cmd/utils/logconfig.go
  rpcapi/txpool.go
  txpool/handler.go
  txpool/txpool.go
Labels: bug

#357 add use default block gaslimit
  blockchain/blockchain.go
  blockchain/genesis.go
  blockchain/test_utils.go
  build/genesis.json
  consensus/consensus.go
  consensus/miner/worker.go
  params/params.go
  processor/evm.go
Labels: bug

#361 p2p/discover/udp.go: findnode return at least 1 bootnode
  p2p/discover/udp.go
Labels: bug, duplicate

#363 modify txpool rpc interface
  accountmanager/accountmanager.go
  cmd/ft/txpool.go
  cmd/ft/utils.go
  ftservice/apibackend.go
  p2p/discover/udp.go
  rpcapi/backend.go
  rpcapi/blockchain.go
  rpcapi/txpool.go
Labels: enhancement

#365 start node with fork id
  accountmanager/accountmanager.go
  asset/asset.go
  blockchain/forkcontroller.go
  blockchain/forkcontroller_test.go
  blockchain/genesis.go
Labels: enhancement

#368 add get pending transaction
  cmd/ft/txpool.go
  rpcapi/txpool.go
Labels: enhancement

#371 fix SetupGenesisBlock func return result
  .goreleaser.yml
  blockchain/gen_genesis.go
  blockchain/gen_genesis_test.go
  blockchain/genesis.go
  blockchain/genesis_test.go
Labels: bug

#377 Fix rpc arg check
  ftservice/apibackend.go
  rpcapi/backend.go
  rpcapi/blockchain.go
Labels: bug

#375 Txs broadcast cfg
  build/eg_config.yaml
  cmd/ft/flags.go
  txpool/config.go
  txpool/handler.go
Labels: enhancement
