Repository fractalplatform/fractal, pull requests merged in 2019-02, with the labels that each got.

#18 dpos trigger
  consensus/dpos/vote.go
Labels: bug

#19 split action type field
  blockchain/blockchain.go
  types/action.go
Labels: enhancement

#21 add types package notes and uint test, fix log rpc marshal
  blockchain/test_utils.go
  consensus/dpos/dpos.go
  node/node_test.go
  processor/validator.go
  types/action.go
  types/action_test.go
  types/block.go
  types/block_test.go
  types/bloom9.go
  types/log.go
  types/log_test.go
  types/optinfo.go
  types/receipt.go
  types/receipt_test.go
  types/signer_test.go
  types/transaction.go
  types/transaction_test.go
Labels: bug

#23 change timeout of download request
  blockchain/downloader.go
Labels: bug

#26 Feature genesis bootnodes
  blockchain/genesis.go
  blockchain/genesis_test.go
  build/genesis.json
  ftservice/ftservice.go
  node/node.go
  node/service.go
  params/chainconfig.go
Labels: enhancement

#28 fix receipts root different err
  types/block.go
  types/receipt.go
Labels: bug

#30 update consensus/miner/work
  consensus/miner/worker.go
Labels: bug

#27 reduce event's mutex competition
  blockchain/handler.go
  blockchain/test_utils.go
  cmd/ft/root.go
  event/router.go
  event/router_test.go
  node/node_test.go
  txpool/test_utils.go
  txpool/txpool_test.go
Labels: bug

#31 fix testnet genesis
  build/testnet.json
  consensus/miner/worker.go
  node/node.go
  p2p/dial_test.go
  p2p/protoadaptor/ProtoAdaptor.go
  p2p/server.go
  p2p/server_test.go
Labels: bug

#32 update readme.md
  README.md
  build/config.yaml
  cmd/ft/root.go
Labels: enhancement

#40 add some functionality for wallet and blockchain broswer
  .gitignore
  accountmanager/account.go
  cmd/ft/default.go
  ftservice/ftservice.go
  internal/api/blockchain.go
  internal/api/keystore.go
  wallet/cache/account.go
  wallet/cache/accountcache.go
  wallet/keystore/keyjson.go
  wallet/keystore/keystore.go
  wallet/wallet.go
Labels: enhancement

#42 Change env script
  Makefile
  accountmanager/account.go
  accountmanager/account_test.go
  accountmanager/accountmanager_test.go
  accountmanager/error.go
  accountmanager/interface.go
  asset/asset.go
  asset/asset_object.go
  asset/asset_object_test.go
  asset/asset_test.go
  asset/error.go
  blockchain/genesis.go
  blockchain/protocol.go
  build/env.sh
  cmd/ft/default.go
  internal/api/account.go
  internal/api/blockchain.go
  internal/api/keystore.go
  params/chainconfig.go
  params/gas_table.go
  processor/transition.go
  processor/vm/opcodes.go
  test/tx/main.go
  types/action.go
  utils/trie/hasher.go
  vendor/github.com/ethereum/go-ethereum/crypto/sha3/LICENSE
  vendor/github.com/ethereum/go-ethereum/crypto/sha3/PATENTS
  vendor/github.com/ethereum/go-ethereum/crypto/sha3/doc.go
  vendor/github.com/ethereum/go-ethereum/crypto/sha3/hashes.go
  vendor/github.com/ethereum/go-ethereum/crypto/sha3/keccakf.go
  vendor/github.com/ethereum/go-ethereum/crypto/sha3/keccakf_amd64.go
  vendor/github.com/ethereum/go-ethereum/crypto/sha3/keccakf_amd64.s
  vendor/github.com/ethereum/go-ethereum/crypto/sha3/register.go
  vendor/github.com/ethereum/go-ethereum/crypto/sha3/sha3.go
  vendor/github.com/ethereum/go-ethereum/crypto/sha3/shake.go
  vendor/github.com/ethereum/go-ethereum/crypto/sha3/xor.go
  vendor/github.com/ethereum/go-ethereum/crypto/sha3/xor_generic.go
  vendor/github.com/ethereum/go-ethereum/crypto/sha3/xor_unaligned.go
  vendor/gopkg.in/check.v1/benchmark.go
  vendor/gopkg.in/yaml.v2/readerc.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/sorter.go
  vendor/vendor.json
  wallet/cache/account.go
  wallet/cache/accountcache.go
  wallet/wallet.go
Labels: enhancement

#43 modify sync block log
  blockchain/blockchain.go
  blockchain/blockchain_insert.go
Labels: invalid

#44 Nodefinder
  .gitignore
  Makefile
  blockchain/downloader.go
  blockchain/handler.go
  build/bin/README.md
  build/env.sh
  cmd/ft/root.go
  cmd/ftfinder/config.go
  cmd/ftfinder/ftfinder.go
  cmd/ftfinder/root.go
  event/router.go
  event/router_test.go
  internal/api/p2p.go
  p2p/dial.go
  p2p/discover/node.go
  p2p/discover/udp.go
  p2p/discover/udp_test.go
  p2p/enode/node.go
  p2p/protoadaptor/ProtoAdaptor.go
  p2p/protoadaptor/README.md
  p2p/rlpx.go
  p2p/rlpx_test.go
  p2p/server.go
  p2p/server_test.go
  test.sh
  txpool/handler.go
  txpool/txpool.go
Labels: enhancement

#45 Mod sync log
  blockchain/blockchain.go
  blockchain/blockchain_insert.go
Labels: invalid
